### ISSUE TITLE
Could not load from Plugin Manager in 1.3.9 

### ISSUE THREAD

**Issue by nionio6915** [mtowara/OctoPrint-Gcodebar#2]
I was not able to load the plugin via the plugin manager. 
![image](https://user-images.githubusercontent.com/17693150/43595632-cd80a922-9642-11e8-8690-377a773ed70a.png)

I first tried it by the plugin manager, then did it manually to install, then tried via the plugin manager again to get the screenshot. 
Attached are my logs-
[plugin_firmwareupdater_console.log](https://github.com/mtowara/OctoPrint-Gcodebar/files/2254210/plugin_firmwareupdater_console.log)
[octoprint (2).log](https://github.com/mtowara/OctoPrint-Gcodebar/files/2254211/octoprint.2.log)

I could not see anywhere in the logs the failed install attempts via the plugin manager, only the successful one.

**Comment by mtowara** [comment]
hmm, it still works for me, I'll investigate!

**Comment by mtowara** [comment]
you've got the following in the log, so it looks okay:
2018-08-02 15:50:38,399 - octoprint.plugins.pluginmanager - INFO - The plugin was installed successfully: Gcodebar Plugin, version 0.1.4

Did you try to reload?
Also your screenshot is not for my extension?!
